# Generated by Django 2.0.2 on 2024-05-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20240503_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='insumos_categorys',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Insumos',
        ),
    ]
