# Generated by Django 2.0.2 on 2024-05-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20240503_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['supply_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='supply_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_state',
            new_name='supply_initial_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='supply_input',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='supply_name',
        ),
        migrations.AddField(
            model_name='product',
            name='supply_output',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_total',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_unit',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
