# Generated by Django 2.0.2 on 2024-05-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20240503_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supply_code',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
