# Generated by Django 2.0.2 on 2024-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20240503_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supply_initial_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_input',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_output',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
