# Generated by Django 2.0.2 on 2024-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20240503_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_code',
            field=models.CharField(blank=True, max_length=240, primary_key=True, serialize=False, unique=True),
        ),
    ]
