# Generated by Django 2.0.2 on 2024-05-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20240526_2322'),
        ('inventario', '0023_auto_20240526_2009'),
    ]

    operations = [
    ]
