# Generated by Django 2.0.2 on 2024-05-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20240526_2231'),
        ('inventario', '0024_merge_20240531_0901'),
    ]

    operations = [
    ]
