# Generated by Django 2.0.2 on 2024-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_venta',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_orden', models.CharField(max_length=100)),
                ('producto_orden', models.CharField(max_length=100)),
                ('cantidad_orden', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('agregados', models.PositiveIntegerField()),
            ],
        ),
    ]
