# Generated by Django 2.0.2 on 2024-05-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_orden_venta_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden_venta',
            old_name='monto',
            new_name='monto_orden',
        ),
    ]
