# Generated by Django 2.0.2 on 2024-05-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20240515_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_venta',
            name='agregados_orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
