# Generated by Django 2.0.2 on 2024-05-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_orden_venta_agregados_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='agregados_orden',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='cantidad_orden',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='cliente_orden',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='monto_orden',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='producto_orden',
        ),
        migrations.RemoveField(
            model_name='prod_venta',
            name='agregados',
        ),
        migrations.RemoveField(
            model_name='prod_venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='prod_venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='cliente_venta',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='total_venta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prod_venta',
            name='nombre_producto',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prod_venta',
            name='precio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orden_venta',
            name='numero_orden',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='producto',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Prod_venta'),
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='id_venta_producto',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta_producto'),
        ),
    ]
