# Generated by Django 2.0.2 on 2024-05-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20240520_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_venta',
            name='numero_orden',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
