# Generated by Django 2.0.2 on 2024-05-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20240520_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_venta',
            name='numero_orden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
