# Generated by Django 2.0.2 on 2024-05-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20240505_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_orden', models.CharField(max_length=100)),
                ('producto_orden', models.CharField(max_length=100)),
                ('unidad_orden', models.CharField(max_length=100)),
                ('cantidad_orden', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
