# Generated by Django 2.0.2 on 2024-05-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_orden_compra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='unidad_orden',
        ),
    ]
