# Generated by Django 2.0.2 on 2024-05-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_remove_orden_compra_unidad_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='cantidad_orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='proveedor_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
