# Generated by Django 2.0.2 on 2024-05-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_auto_20240515_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='proveedor_orden',
            field=models.CharField(max_length=100),
        ),
    ]
