# Generated by Django 2.0.2 on 2024-05-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_auto_20240515_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='cantidad_orden',
            field=models.CharField(max_length=100),
        ),
    ]
