# Generated by Django 2.0.2 on 2024-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_auto_20240517_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='proveedor_complete_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='producto_orden',
            field=models.CharField(max_length=100),
        ),
    ]
