# Generated by Django 2.0.2 on 2024-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0012_auto_20240517_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_complete_name',
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='cantidad_orden',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='proveedor_orden',
            field=models.CharField(max_length=100),
        ),
    ]
