# Generated by Django 2.0.2 on 2024-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0016_auto_20240517_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='cantidad_orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
