# Generated by Django 2.0.2 on 2024-05-18 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20240503_2125'),
        ('proveedores', '0017_auto_20240517_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_orden', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orden_compra',
            name='cantidad_orden',
        ),
        migrations.RemoveField(
            model_name='orden_compra',
            name='producto_orden',
        ),
        migrations.AddField(
            model_name='producto_orden',
            name='orden_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Orden_compra'),
        ),
        migrations.AddField(
            model_name='producto_orden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product'),
        ),
    ]
