# Generated by Django 2.0.2 on 2024-05-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0018_auto_20240517_2150'),
        ('proveedores', '0011_proveedor_proveedor_insumo'),
    ]

    operations = [
    ]
