# Generated by Django 2.0.2 on 2024-05-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0019_merge_20240517_2323'),
        ('proveedores', '0019_merge_20240517_2315'),
    ]

    operations = [
    ]
