# Generated by Django 2.0.2 on 2024-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0020_merge_20240518_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_insumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
