# Generated by Django 2.0.2 on 2024-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0020_merge_20240518_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
