# Generated by Django 2.0.2 on 2024-05-23 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0021_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
