# Generated by Django 2.0.2 on 2024-05-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0021_auto_20240522_2224'),
        ('proveedores', '0022_auto_20240522_2221'),
    ]

    operations = [
    ]
