# Generated by Django 2.0.2 on 2024-05-25 05:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0023_merge_20240524_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_insumo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None),
        ),
    ]
