# Generated by Django 2.0.2 on 2024-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0024_auto_20240525_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
