# Generated by Django 2.0.2 on 2024-05-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0024_auto_20240525_0102'),
        ('proveedores', '0025_orden_compra_monto'),
    ]

    operations = [
    ]
