# Generated by Django 2.0.2 on 2024-05-25 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0026_merge_20240525_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_insumo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
