# Generated by Django 2.0.2 on 2024-05-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0024_auto_20240524_1957'),
        ('proveedores', '0027_auto_20240525_0433'),
    ]

    operations = [
    ]
