# Generated by Django 2.0.2 on 2024-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0029_auto_20240525_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='proveedor_activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
