# Generated by Django 2.0.2 on 2024-05-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0030_proveedor_proveedor_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_activo',
        ),
    ]
