# Generated by Django 2.0.2 on 2024-05-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0023_merge_20240524_1411'),
        ('proveedores', '0031_remove_proveedor_proveedor_activo'),
    ]

    operations = [
    ]
