# Generated by Django 2.0.2 on 2024-05-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20240526_2322'),
        ('proveedores', '0031_remove_proveedor_proveedor_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prov_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_insumo',
        ),
        migrations.AddField(
            model_name='prov_prod',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
