# Generated by Django 2.0.2 on 2024-05-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0032_auto_20240531_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
    ]
