# Generated by Django 2.0.2 on 2024-05-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0033_auto_20240531_1418'),
        ('proveedores', '0032_merge_20240526_2231'),
    ]

    operations = [
    ]
